baseURL: https://kacpermalachowski.pl/
title: Kacper Małachowski
pagination:
  pagerSize: 5
theme: PaperMod
defaultContentLanguage: pl
defaultContentLanguageInSubdir: false

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Kacper Małachowski
  description: Kacper Małachowski - blog o programowaniu, technologiach i życiu
  author: Kacper Małachowski
  DateFormat: "02-01-2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  ShowFullTextinRSS: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  socialIcons:
    - name: github
      url: https://github.com/KacperMalachowski
    - name: linkedin
      url: https://www.linkedin.com/in/kacper-małachowski-940b6919b
    - name: stackoverflow
      url: https://stackoverflow.com/users/23148781/kacper-ma%C5%82achowski
    - name: rss
      url: /index.xml

pygmentsUseClasses: true

permalinks:
  posts: /posts/:slug/
  pages: /:slug/

markup:
  highlight:
    noClasses: false