# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      ci-dependencies:
        update-types:
        - "minor"
        - "patch"

  # Maintain dependencies for npm
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      tf-dependencies:
        update-types:
        - "minor"
        - "patch"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        update-types:
        - "minor"
        - "patch"