# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      ci-dependencies:
        update-types:
        - "minor"
        - "patch"
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      npm-production-dependencies:
        dependency-type: "production"
        update-types:
        - "minor"
        - "patch"
      npm-dev-dependencies:
        dependency-type: "development"
        update-types:
        - "minor"
        - "patch"