baseURL: "https://kacpermalachowski.pl"
languageCode: "en-US"
title: "Kacper Malachowski"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

enableEmoji: true

params:
  title: Kacper Malachowski
  description: Text about my cool site
  useBootstrapCDN: true
  animate: true
  favicon: "/fav.png"

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Kacper Małachowski" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Kacper."
    subtitle: "I help developers in they work"
    content: "A passionate DevSecOps Engineer. I tend to build tools that helps achieve fast, reliable and secure way for the software from the first line of code."
    image: /images/hero.jpg
    button:
      enable: true
      name: "Resume"
      url: "resume.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: "https://github.com/KacperMalachowski"
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/kacper-ma%C5%82achowski-940b6919b/
    
  about:
    enable: true
    title: "About Me"
    image: /images/hero.jpg
    content: |-
      I am a software engineer with a passion for cybersecurity. I graduated from engineer degree in 2024, starting master degree same year.

      Currently I'm working as a team member in kyma project in SAP since July 2022. My main role is to help developers work smoothly and in complaiant way against company standards.

      Privately, I'm big enthuastiast of USA and aviation, I'm also a mmeber of PaffsAir virtual airline.

      My engineer thesis topic was about system for virtual airlines managment based on Microsoft Flight Simulator 2020. 
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Prow"
        - "Google Cloud Platform"
        - "Azure DevOps"
        - "Github Actions"
        - "Terraform/Tofu"
        - "Go"
        - "Docker"
        - "Kubernetes"
        - "Renovate/Dependabot"
        - "Kubernetes"
    
  experience:
    enable: true
    items:
      - job: "DevSecOps"
        company: "SAP"
        companyUrl: "https://sap.com"
        date: "July 2022 - present"
        info:
          enable: false
        featureLink:
          enable: true
          name: "View the Kyma Project"
          url: https://kyma-project.io/
        content: "I'm currently working as a DevSecOps at [SAP Lab Poland](https://sap.com) in Gliwice."
      - job: "IT trener"
        company: "Coding Giants"
        companyUrl: https://www.codinggiants.com
        date: "Dec 2022 - July 2022"
        info:
          enable: false
        content: "I was a IT trener, teaching teenagers about software development using simple language and tools"
  education:
    enable: true
    index: false
    items:
      - title: "Engineer of Science in Computer Science"
        school:
          name: "University of Silesia"
          url: "https://us.edu.pl"
        date: "2020-2024"
        GPA: "5.0 of 5.0"

  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:kacpermaachowski@gmail.com

  footer:
    recentPosts:
      path: blogs
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/KacperMalachowski
      linkedin: https://www.linkedin.com/in/kacper-ma%C5%82achowski-940b6919b/

  listPages:
    disableFeaturedImage: false
  
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"
    
  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"