main:
  - identifier: posts
    name: Posts
    url: posts
    weight: 30
  - identifier: about
    name: About Me
    url: about
    weight: 50
  - identifier: archives
    name: Archives
    url: archives
    weight: 60