main:
  - identifier: posts
    name: Blog
    url: /posts/
    weight: 30
  - identifier: projects
    name: Projekty
    url: /projects/
    weight: 30
  - identifier: about
    name: O mnie
    url: /about/
    weight: 50
  - identifier: archives
    name: Archiwum
    url: /archives/
    weight: 60