name: build-strapi

on:
  push:
    branches:
      - main
    paths:
      - "cms/**"
      - ".github/workflows/build-strapi.yml"
  pull_request:
    branches:
      - main
    paths:
      - "cms/**"
      - ".github/workflows/build-strapi.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/strapi

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare tags
        id: prepare-tags
        run: |
          tags=()

          if [[ "${{ github.event_name }}" == 'pull_request' ]]
            tags+=(ref,event=pull-request,prefix=pr-)
          else
            tags+=(type=sha,prefix={{date 'YYYYMMDD'}}-,enable={{is_default_branch}})
            tags+=(type=raw,value=latest,enable={{is_default_branch}})
          fi

          echo "tags=$(IFS=$'\n'; echo "${tags[*]}")" >> $GITHUB_OUTPUT

      - name: Extract metadata for docker
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ steps.prepare-tags.outputs.tags }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: cms
          file: cms/Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
