name: build-strapi

on:
  push:
    branches:
      - main
    paths:
      - "cms/**"
      - ".github/workflows/build-strapi.yml"
  pull_request:
    branches:
      - main
    paths:
      - "cms/**"
      - ".github/workflows/build-strapi.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/strapi

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for docker
        id: metadata-push
        if: ${{ github.event_name == 'push' }}
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{date 'YYYYMMDD'}}-
            type=raw,value=latest

      - name: Extract metadata for docker
        id: metadata-pr
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=pull-request,prefix=pr-

      - name: Set metadata outputs
        id: metadata
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "tags=${{ steps.metadata-push.outputs.tags }}" >> $GITHUB_OUTPUT
            echo "labels=${{ steps.metadata-push.outputs.labels }}" >> $GITHUB_OUTPUT
          else
            echo "tags=${{ steps.metadata-pr.outputs.tags }}" >> $GITHUB_OUTPUT
            echo "labels=${{ steps.metadata-pr.outputs.labels }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: cms
          file: cms/Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
