name: Build Docker Image 

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        side: [
          { 
            name: 'website', 
            context: './client', 
            dockerfile: './client/Dockerfile',
            update_webhook: 'https://portainer.kacpermalachowski.pl/api/webhooks/1e100b68-8b18-4384-8d2c-4ca1900c27db'
          },
          { 
            name: 'api', 
            context: './server', 
            dockerfile: './server/Dockerfile',
            update_webhook: 'https://portainer.kacpermalachowski.pl/api/webhooks/c4d36782-85ea-4388-bbfb-8b5aa7274c5f'
          }
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
         
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: europe-central2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: europe-central2-docker.pkg.dev/blog-395007/blog/${{ matrix.side.name }}
          tags: |
            type=sha,format=short
            type=schedule
            type=raw,latest

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ${{ matrix.side.context }}
          file: ${{ matrix.side.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}