name: pull-infracost

on:
  pull_request_target:

jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    env:
      TF_ROOT: tofu
    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ vars.GH_COM_MALACHOWSKI_BLOG_GCP_WORKLOAD_IDENTITY_FEDERATION_PROVIDER }}
          service_account: ${{ vars.GCP_TOFU_PLANNER_SERVICE_ACCOUNT_EMAIL }}
          create_credentials_file: true
      - name: Retrieve infracost API key
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            infracost-api-key:${{ vars.GCP_BLOG_PROJECT_ID }}/${{ vars.GCP_INFRACOST_API_KEY_SECRET_NAME }}
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ steps.secrets.outputs.infracost-api-key }}
          currency: PLN
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Generate Infracost cost estimate baseline
        run: infracost breakdown --path=${TF_ROOT} --format=json --out-file=/tmp/infracost-base.json
      - name: Checkout PR branch
        uses: actions/checkout@v4
      - name: Generate infracost diff
        run: infracost diff --path=${TF_ROOT} --format=json --compare-to=/tmp/infracost-base.json --out-file=/tmp/infracost.json
      - name: Post infracost comment
        run: infracost comment github --path /tmp/infracost.json --repo ${{github.repository}} --github-token=${{github.token}} --pull-request=${{github.event.pull_request.number}} --behavior=update
        
