name: Spellcheck
permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited
    paths:
      - '**/*.md'
      - '**/*.yaml'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache npm global packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-global-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-global-
      - name: Install cspell and Polish dictionary
        run: |
          npm install -g cspell @cspell/dict-pl_pl
          
          cspell link add @cspell/dict-pl_pl
      - name: Run cspell
        run: cspell --config cspell.config.yaml "**/*.{md,yaml}" --no-progress --language-id=en,pl
