name: Spellcheck
permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install cspell and Polish dictionary
        run: |
          npm install -g cspell
          npm install -g @cspell/dict-pl-pl
      - name: Run cspell
        run: |
          cspell --config cspell.config.yaml "**/*.{md,html,js,ts,css,yaml}" --no-progress --language-id=en,pl
