name: Run Tests on pull request for Vue Client

on:
  pull_request:
    paths:
      - 'client/**'
      - .github/workflows/test-client.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        working-directory: ./client
        run: npm install
      - name: Lint
        working-directory: ./client
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        working-directory: ./client
        run: npm install
      - name: Test
        working-directory: ./client
        run: npm run test:unit

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        working-directory: ./client
        run: npm install
      - name: Format
        working-directory: ./client
        run: npm run format

  e2e:
    runs-on: ubuntu-latest
    services:
      api:
        image: ghcr.io/kacpermalachowski/blog/server:main
        ports:
          - 3000:3000
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog
          POSTGRES_HOST: postgres
      postgres:
        image: postgres:13.3
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        working-directory: ./client
        run: npm install
      - name: E2E
        working-directory: ./client
        run: npm run test:e2e
  