name: 'Terraform Apply'

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/tf-apply.yml
      - infra/**
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

env:
  CONFIG_DIRECTORY: "./infra"

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform Apply
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Terraform Init
        working-directory: ${{ env.CONFIG_DIRECTORY }}
        run: terraform init -input=false -no-color

      - name: Terraform Apply
        working-directory: ${{ env.CONFIG_DIRECTORY }}
        run: terraform apply -auto-approve
      